services:
  frontend:
    container_name: frontend-react
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - network
  backend:
    container_name: backend-spring
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - network
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - network
networks:
  network:
