services:

  # Frontend
  frontend:
    container_name: frontend-react
    build: ./frontend
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
        - frontend-network

  # Backend
  backend:
    container_name: backend-spring
    build: ./backend
    environment:
      - DB_SERVER=database-postgres
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
        - backend-network
        - frontend-network

  # Database
  database:
    container_name: database-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
        - backend-network
volumes:
    node_modules:

networks:
    frontend-network:
      name: frontend-network

    backend-network:
      name: backend-network