services:

  # Frontend
  frontend:
    container_name: frontend-react
    build: ./frontend
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - network
    volumes:
      - ./frontend:/app

  # Backend
  backend:
    container_name: backend-spring
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - network
    volumes:
      - ./backend:/app

  # Database
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - network
    volumes:
      - ./database:/app
networks:
  network:

volumes:
  node_modules: